version: "3.3"

services:
  tkdnn_2:
    image: "registry.learning-loop.ai/loop_tkdnn:${TAG-latest}"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    build:
      context: .
      dockerfile: tkdnn.dockerfile
      args:
        MAKEFLAGS: "-j6"
    command: "tail -f /dev/null"
    volumes:
      - ./test_data:/data
      - ./tkdnn_python/darknet_rt.py:/tkDNN/darknet_rt.py
      - ./tkdnn_python/darknetRT.h:/tkDNN/demo/demo/darknetRT.h
      - ./tkdnn_python/darknetRT.cpp:/tkDNN/demo/demo/darknetRT.cpp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu, utility]